### ISSUE TITLE
Adding "Loading" Pop-up ?

### ISSUE THREAD

**Issue by sylvainar** [WikiJourney/wikijourney_app#38]
I think we should add a "Loading" pop-up during GPS loading and during the network call, like : 
- Waiting for your position...
- Looking for POIs around... 

So it doesn't look like the app has crashed down.

**Comment by nymous** [comment]
Or a SnackBar (because Material design :smile: )

**Comment by sylvainar** [comment]
Yup :heart:

**Comment by nymous** [comment]
Fixed in 862768b144a7ab9b7004e7666334d5328d4bc124
