### ISSUE TITLE
"Go" button seems to be useless

### ISSUE THREAD

**Issue by sylvainar** [WikiJourney/wikijourney_app#39]
When I type a destination and then click on "Go", the app looks for POIs around me...

**Comment by nymous** [comment]
This is not a bug, it is not implemented...

**Comment by sylvainar** [comment]
Lol x)

**Comment by sylvainar** [comment]
Okay no problem

**Comment by nymous** [comment]
Fixed in 7d17b754266abbd54b61a57da19a23538585e845
