### ISSUE TITLE
Android app crashes due to json error

### ISSUE THREAD

**Issue by k3b** [WikiJourney/wikijourney_app#87]
When i start the android app from a  german android device and search for "Hannover"

the app calls "http://api.wikijourney.eu/?place=hannover&maxPOI=25&range=1.0&lg=de"

which will return illegal json that let the app crash

some of the poi_info-array elements are booleans  

<pre>
{
    "infos": {
        "source": "WikiJourney API",
        "link": "http:\/\/wikijourney.eu\/",
        "api_version": "Beta 1.1.2"
    },
    "user_location": {
        "latitude": "52.3744779",
        "longitude": "9.7385532"
    },
    "poi": 
        {
            "nb_poi": 25,
            "poi_info": [{
                "id": "1715",
                "latitude": "52.3744",
                ...
                "lastupdate": "2016-03-21"
            }, 
!!!! error start here
            false, 
            false, 
            false, 
            false, 
            {
                "id": "314082",
                "latitude": "52.3656",
...
</pre>

**Comment by sylvainar** [comment]
Fixed on the repository of the API !
https://github.com/WikiJourney/wikijourney_api/commit/038f4746c2238c99d0f37723f30dfd2755382fd1

Thanks for reporting !

**Comment by k3b** [comment]
Now it works again. thanks for fast fixing
