### ISSUE TITLE
map is not shown

### ISSUE THREAD

**Issue by tclavier** [WikiJourney/wikijourney_app#97]
Step to reproduce : 
- launch wiki journey app, 
- click on "find around my position", 
- you just see a background with a grid and positions markers
  I want to see open street map with positions markers.

**Comment by sylvainar** [comment]
Hey !

We're gonna take a look at this. This is not normal, it's probably a bug from OSM but we'll make further investigations.

Meanwhile, you can try it on http://wikijourney.eu !

Thanks for your comment :wink:

**Comment by nymous** [comment]
Hi @tclavier, I tried to reproduce on my phone, I got the error once but nothing more.
This is probably a problem on OSM side, did you try the day after?

**Comment by tclavier** [comment]
I just test now, and that work find. I used wiki journey with this bug during 4 days before report it. 
It's possible to have an alternate map ?
